import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { compileStartup } from '../scripts/compile_startup.mjs';
const root = process.argv[2];
const source = ['MAP','STATE','TABLES'].map(v => JSON.parse(readFileSync(`${root}/${v}.json`,'utf8')));
source.push(readFileSync(`${root}/tenantData.txt`,'utf8'));
source.push(readFileSync(`${root}/LOADED_MAP.tsv`,'utf8'),readFileSync(`${root}/LOADED_INSTANCES.tsv`,'utf8'));
assert.match(compileStartup(...source), /const StartupData &startup_data/);
const reject = edit => { const v=structuredClone(source); edit(v); assert.throws(()=>compileStartup(...v)); };
reject(([m])=>m.cells.pop()); reject(([m])=>m.cells[0][0]=[999,0]);
reject(([m])=>m.cells[0][0][1]=-1); reject(([m])=>m.unread_tail_hex='');
reject(([,s])=>s.resources.money=10000); reject(([,s])=>s.initial_catalog[0].id=29);
reject(([,s])=>s.initial_catalog[2].construction_counter_threshold=400);
reject(([,s])=>s.map_seed_instances[0].x=-1); reject(([,s])=>s.first_arrival.definition_id=0);
reject(([,,t])=>t.entries[0].source_utf8+='x'); reject(([,,t])=>t.apk_sha256='other');
reject(([,s])=>s.first_arrival.equipment_ids.pop());
reject(([,s])=>s.reset.unlocked_character_definitions=[1]);
reject(v=>v[3]=v[3].replace('300\t450','301\t450'));
reject(v=>v[4]=v[4].replace('route_category','category'));
reject(v=>v[4]=v[4].split('\n').slice(0,-2).join('\n')+'\n');
reject(v=>v[4]=v[4].replace('0\t0\t15','1\t0\t15'));
reject(v=>v[4]=v[4].replace('\t-1\t0\n','\t0\t1\n'));
reject(v=>v[5]=v[5].replace('0\t2\t3','0\t2\t4'));
reject(v=>v[5]=v[5].replace('1\t3\t4','1\t2\t3'));
reject(v=>v[5]=v[5].replace('83\t11\t10','83\t24\t10'));
reject(v=>v[4]=v[4].replace('0\t0\t15\t12\t3','0\t0\t15\t12\t9'));
console.log('PASS startup data and 22 rejection cases');
