# 三个研究包共享构建策略；日常常驻Release，按需Debug，均动态链接。
# 不修改产品构建，不按Release名字自动切换静态分发。
include_guard(GLOBAL)

# 单配置入口默认Release；显式Debug等配置保持原值。多配置生成器构建时指定--config。
if(NOT CMAKE_CONFIGURATION_TYPES AND NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Release CACHE STRING "研究构建配置；日常Release，Debug按需" FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS Debug Release RelWithDebInfo MinSizeRel)
endif()

option(BUILD_SHARED_LIBS "研究日常构建使用共享库；静态仅用于单独配置的Release分发" ON)
if(NOT BUILD_SHARED_LIBS AND NOT CMAKE_BUILD_TYPE STREQUAL "Release")
    message(FATAL_ERROR "研究非分发构建应启用BUILD_SHARED_LIBS；静态分发请使用独立Release构建目录")
endif()

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib")
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
set(CMAKE_BUILD_RPATH_USE_ORIGIN ON)
if(APPLE)
    set(CMAKE_BUILD_RPATH "@loader_path")
elseif(UNIX)
    set(CMAKE_BUILD_RPATH "$ORIGIN")
endif()
if(BUILD_SHARED_LIBS AND (MSVC OR CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC"))
    set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
endif()

if(BUILD_SHARED_LIBS AND MINGW)
    # 历史cache用-static规避错架构DLL；切共享后不能悄悄保留或覆盖该缓存值。
    foreach(research_flag_variable IN ITEMS CMAKE_CXX_FLAGS CMAKE_EXE_LINKER_FLAGS
            CMAKE_SHARED_LINKER_FLAGS CMAKE_MODULE_LINKER_FLAGS)
        foreach(research_suffix IN ITEMS "" _DEBUG _RELEASE _RELWITHDEBINFO _MINSIZEREL)
            if("${${research_flag_variable}${research_suffix}}" MATCHES
                    "(^|[ ;])-static($|[ ;]|-libstdc\\+\\+|-libgcc)")
                message(FATAL_ERROR
                    "动态研究构建检测到${research_flag_variable}${research_suffix}中的静态链接选项；请显式清空旧cache flag（例如-DCMAKE_EXE_LINKER_FLAGS=），不要沿用旧-static")
            endif()
        endforeach()
    endforeach()
endif()

function(dungeon_village_library target)
    get_target_property(research_kind "${target}" TYPE)
    if(MINGW AND research_kind STREQUAL "SHARED_LIBRARY")
        # WINDOWS_EXPORT_ALL_SYMBOLS是MS工具的def生成策略；MinGW用其链接器导出机制。
        target_link_options("${target}" PRIVATE "LINKER:--export-all-symbols")
    endif()
endfunction()

function(dungeon_village_check_dll dll)
    # 不能从host编译器bin盲拷：LLVM-MinGW宿主x64和目标i686有同名不同架构DLL。
    file(READ "${dll}" research_dos OFFSET 0 LIMIT 2 HEX)
    file(READ "${dll}" research_offset OFFSET 60 LIMIT 4 HEX)
    string(LENGTH "${research_offset}" research_offset_length)
    if(NOT research_dos STREQUAL "4d5a" OR NOT research_offset_length EQUAL 8 OR
       NOT research_offset MATCHES "^[0-9a-fA-F]+$")
        message(FATAL_ERROR "不是有效Windows运行库：${dll}")
    endif()
    string(SUBSTRING "${research_offset}" 0 2 research_b0)
    string(SUBSTRING "${research_offset}" 2 2 research_b1)
    string(SUBSTRING "${research_offset}" 4 2 research_b2)
    string(SUBSTRING "${research_offset}" 6 2 research_b3)
    math(EXPR research_pe_offset "0x${research_b3}${research_b2}${research_b1}${research_b0}")
    file(READ "${dll}" research_pe OFFSET ${research_pe_offset} LIMIT 6 HEX)
    string(LENGTH "${research_pe}" research_pe_length)
    if(NOT research_pe_length EQUAL 12)
        message(FATAL_ERROR "运行库PE头被截断：${dll}")
    endif()
    string(SUBSTRING "${research_pe}" 0 8 research_signature)
    string(SUBSTRING "${research_pe}" 8 4 research_machine)
    if(NOT research_signature STREQUAL "50450000")
        message(FATAL_ERROR "运行库缺PE签名：${dll}")
    endif()
    set(research_architecture "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
    if(CMAKE_CXX_COMPILER_TARGET)
        set(research_architecture "${CMAKE_CXX_COMPILER_TARGET}")
    elseif(MINGW)
        execute_process(COMMAND "${CMAKE_CXX_COMPILER}" -dumpmachine
            RESULT_VARIABLE research_arch_result OUTPUT_VARIABLE research_architecture
            OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(NOT research_arch_result EQUAL 0)
            message(FATAL_ERROR "无法读取MinGW目标架构以检查${dll}")
        endif()
    endif()
    string(TOLOWER "${research_architecture}" research_architecture)
    if(research_architecture MATCHES "^(aarch64|arm64)")
        set(research_expected_machine "64aa")
    elseif(research_architecture MATCHES "^arm")
        set(research_expected_machine "c401")
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(research_expected_machine "4c01")
    else()
        set(research_expected_machine "6486")
    endif()
    if(NOT research_machine STREQUAL research_expected_machine)
        message(FATAL_ERROR "运行库架构与当前${CMAKE_SIZEOF_VOID_P}字节指针目标不符：${dll} (PE machine ${research_machine})")
    endif()
endfunction()

function(dungeon_village_copy_runtime dll)
    dungeon_village_check_dll("${dll}")
    get_filename_component(research_name "${dll}" NAME)
    # 单配置一份；多配置各bin/<配置>一份，不按每个测试可执行文件重复复制。
    if(CMAKE_CONFIGURATION_TYPES)
        foreach(research_configuration IN LISTS CMAKE_CONFIGURATION_TYPES)
            set(research_output "${CMAKE_BINARY_DIR}/bin/${research_configuration}")
            file(MAKE_DIRECTORY "${research_output}")
            configure_file("${dll}" "${research_output}/${research_name}" COPYONLY)
        endforeach()
    else()
        file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/bin")
        configure_file("${dll}" "${CMAKE_BINARY_DIR}/bin/${research_name}" COPYONLY)
    endif()
endfunction()

if(BUILD_SHARED_LIBS AND MINGW)
    set(DUNGEON_VILLAGE_MINGW_RUNTIME_DIR "" CACHE PATH
        "可选：当前目标架构MinGW运行库目录；默认从编译器目标导入库定位")
    set(research_runtime_found FALSE)
    foreach(research_runtime IN ITEMS "libc++.dll.a|libc++.dll"
            "libunwind.dll.a|libunwind.dll" "libwinpthread.dll.a|libwinpthread-1.dll")
        string(REPLACE "|" ";" research_pair "${research_runtime}")
        list(GET research_pair 0 research_import_name)
        list(GET research_pair 1 research_dll_name)
        if(DUNGEON_VILLAGE_MINGW_RUNTIME_DIR)
            set(research_dll "${DUNGEON_VILLAGE_MINGW_RUNTIME_DIR}/${research_dll_name}")
        else()
            set(research_compiler_target)
            if(CMAKE_CXX_COMPILER_TARGET)
                list(APPEND research_compiler_target "--target=${CMAKE_CXX_COMPILER_TARGET}")
            endif()
            execute_process(COMMAND "${CMAKE_CXX_COMPILER}" ${research_compiler_target}
                            "-print-file-name=${research_import_name}"
                RESULT_VARIABLE research_lookup_result OUTPUT_VARIABLE research_import
                OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
            if(NOT research_lookup_result EQUAL 0 OR NOT IS_ABSOLUTE "${research_import}" OR
               NOT EXISTS "${research_import}")
                continue()
            endif()
            get_filename_component(research_import_dir "${research_import}" DIRECTORY)
            get_filename_component(research_target_dir "${research_import_dir}" DIRECTORY)
            set(research_dll "${research_target_dir}/bin/${research_dll_name}")
        endif()
        if(NOT EXISTS "${research_dll}")
            message(FATAL_ERROR "缺少当前目标MinGW运行库${research_dll_name}；查找位置：${research_dll}")
        endif()
        dungeon_village_copy_runtime("${research_dll}")
        if(research_dll_name STREQUAL "libc++.dll")
            set(research_runtime_found TRUE)
        endif()
    endforeach()
    if(NOT research_runtime_found)
        message(FATAL_ERROR "未能定位目标LLVM-MinGW libc++动态运行库；请使用完整工具链或显式指定DUNGEON_VILLAGE_MINGW_RUNTIME_DIR")
    endif()
endif()

function(dungeon_village_raylib_runtime)
    if(NOT BUILD_SHARED_LIBS)
        return()
    endif()
    get_target_property(research_raylib_links PkgConfig::RAYLIB INTERFACE_LINK_LIBRARIES)
    foreach(research_library IN LISTS research_raylib_links)
        if(research_library MATCHES "(^|[/\\\\])(lib)?raylib\\.a$")
            message(FATAL_ERROR "共享研究构建仍链接静态raylib：${research_library}；请改用动态raylib的PKG_CONFIG_PATH并清除旧RAYLIB_*、pkgcfg_lib_RAYLIB_*及__pkg_config_checked_RAYLIB缓存")
        endif()
    endforeach()
    if(WIN32)
        set(research_raylib_dll)
        foreach(research_dir IN ITEMS "${RAYLIB_PREFIX}/bin" "${RAYLIB_PREFIX}/lib")
            foreach(research_name IN ITEMS raylib.dll libraylib.dll)
                if(EXISTS "${research_dir}/${research_name}" AND NOT research_raylib_dll)
                    set(research_raylib_dll "${research_dir}/${research_name}")
                endif()
            endforeach()
        endforeach()
        if(NOT research_raylib_dll)
            message(FATAL_ERROR "动态raylib缺少DLL；仅检查PkgConfig RAYLIB_PREFIX=${RAYLIB_PREFIX}的bin/lib，不回退静态库或宿主PATH")
        endif()
        dungeon_village_copy_runtime("${research_raylib_dll}")
        target_compile_definitions(PkgConfig::RAYLIB INTERFACE USE_LIBTYPE_SHARED)
    endif()
endfunction()
