import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { compileStartup } from '../scripts/compile_startup.mjs';
const [root, tenant] = process.argv.slice(2);
const json = name => JSON.parse(readFileSync(`${root}/${name}.json`,'utf8'));
const source = [json('MAP'),json('STATE'),json('TABLES'),readFileSync(tenant,'utf8')];
assert.match(compileStartup(...source), /const StartupEvidence &startup_evidence/);
const reject = edit => { const input=structuredClone(source); edit(input); assert.throws(()=>compileStartup(...input)); };
reject(([m])=>m.cells.pop());
reject(([m])=>m.cells[0][0]=[999,0]);
reject(([m])=>m.cells[0][0]=[14,0]);
reject(([m])=>m.cells[0][0][1]=-1);
reject(([m])=>m.unread_tail_hex='');
reject(([,s])=>s.resources.money=10000);
reject(([,s])=>s.initial_catalog[0].id=29);
reject(([,s])=>s.initial_catalog[2].construction_counter_threshold=400);
reject(([,s])=>s.map_seed_instances[0].x=-1);
reject(([,s])=>s.first_arrival.definition_id=0);
reject(([,s])=>s.first_arrival.equipment_ids[0]=1);
reject(([,s])=>s.first_arrival.job_level=2);
reject(([,s])=>s.reset.unlocked_character_definitions=[1]);
reject(([,,t])=>t.entries[0].source_utf8+='x');
reject(([,,t])=>t.apk_sha256='other');
reject(input=>input[3]+='\n');
console.log('新局数据编译正例与16项拒绝用例通过');
