// One product Unicode inventory feeds the font subset and the runtime text atlas.
// Only authored source/include and shipped text data are scanned, never research
// or generated build trees. The output header remains private build data.
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const digest = bytes => createHash('sha256').update(bytes).digest('hex');
// Consume an encoding signature at byte zero; it is not displayed text. Interior/escaped
// characters remain inventory inputs, and provenance still hashes the original bytes.
const decoder = new TextDecoder('utf-8', { fatal: true, ignoreBOM: false });
const groups = [['src', new Set(['.cpp', '.hpp'])], ['include', new Set(['.hpp'])],
  ['assets', new Set(['.txt', '.tsv', '.json'])]];
const compare = (a, b) => a < b ? -1 : a > b ? 1 : 0;

function collectFiles(directory, suffixes) {
  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const file = path.join(directory, entry.name);
    // Do not follow links into another source package or a generated tree.
    if (entry.isDirectory()) files.push(...collectFiles(file, suffixes));
    else if (entry.isFile() && suffixes.has(path.extname(entry.name))) files.push(file);
  }
  return files.sort(compare);
}

export function collectDesktopGlyphs(root) {
  root = path.resolve(root);
  const points = new Set(Array.from({ length: 95 }, (_, index) => index + 32));
  const inputs = [];
  function addPoint(point, file) {
    if (point < 32 || point === 127) return;
    if (point > 0x10ffff || (point >= 0xd800 && point <= 0xdfff))
      throw new Error('Invalid Unicode scalar in product glyph input: ' + file);
    points.add(point);
  }
  function addText(text, file) {
    for (const character of text) addPoint(character.codePointAt(0), file);
  }
  function addJson(value, file) {
    // JSON decoding joins surrogate pairs and exposes escaped string/key glyphs.
    // Serialization punctuation/numeric spelling is covered by seeded ASCII.
    if (typeof value === 'string') addText(value, file);
    else if (Array.isArray(value)) for (const item of value) addJson(item, file);
    else if (value && typeof value === 'object')
      for (const [key, item] of Object.entries(value)) { addText(key, file); addJson(item, file); }
  }
  for (const [folder, suffixes] of groups)
    for (const file of collectFiles(path.join(root, folder), suffixes)) {
      const bytes = readFileSync(file);
      const relative = path.relative(root, file).split(path.sep).join('/');
      let text;
      try { text = decoder.decode(bytes); }
      catch (error) { throw new Error("Invalid UTF-8 product glyph input: " + relative, { cause: error }); }
      addText(text, relative);
      // Preserve the previous subset scanner's C++/JSON Unicode-escape semantics.
      for (const match of text.matchAll(/\\u([0-9a-fA-F]{4})|\\U([0-9a-fA-F]{8})/g)) {
        const point = Number.parseInt(match[1] ?? match[2], 16);
        if (point < 0xd800 || point > 0xdfff) addPoint(point, relative);
      }
      if (path.extname(file) === '.json') {
        let decoded;
        try { decoded = JSON.parse(text); }
        catch (error) { throw new Error('Invalid JSON product glyph input: ' + relative, { cause: error }); }
        addJson(decoded, relative);
      }
      inputs.push({ file: relative, sha256: digest(bytes) });
    }
  return { schema: 1, codepoints: [...points].sort((a, b) => a - b), inputs };
}

export function desktopGlyphsHeader(inventory) {
  const canonical = JSON.stringify(inventory, null, 2) + '\n';
  const bytes = Buffer.from(inventory.codepoints.map(point => String.fromCodePoint(point)).join(''), 'utf8');
  const literals = [];
  for (let begin = 0; begin < bytes.length; begin += 64)
    literals.push('    "' + [...bytes.subarray(begin, begin + 64)]
      .map(byte => '\\x' + byte.toString(16).padStart(2, '0')).join('') + '"');
  return '// Generated by scripts/compile_desktop_glyphs.mjs; do not edit.\n' +
    '// Unicode inventory SHA-256: ' + digest(canonical) + '\n#pragma once\n\n' +
    'namespace ark::desktop::generated {\ninline constexpr char desktop_glyphs[] =\n' +
    literals.join('\n') + ';\n} // namespace ark::desktop::generated\n';
}

function putOutput(root, output, content) {
  const file = path.resolve(output);
  // An inventory/header must not become its own input on the next scan.
  for (const folder of ['src', 'include', 'assets', 'research']) {
    const relative = path.relative(path.join(root, folder), file);
    if (!relative || (!relative.startsWith('..' + path.sep) && relative !== '..' && !path.isAbsolute(relative)))
      throw new Error('Glyph output must stay outside product source/data and research: ' + file);
  }
  const bytes = Buffer.from(content, 'utf8');
  if (existsSync(file) && readFileSync(file).equals(bytes)) return;
  mkdirSync(path.dirname(file), { recursive: true });
  writeFileSync(file, bytes);
}

function main() {
  const args = process.argv.slice(2), options = new Map();
  for (let index = 0; index < args.length; index += 2) {
    const key = args[index], value = args[index + 1];
    if (!['--root', '--json', '--header'].includes(key) || !value || value.startsWith('--') || options.has(key))
      throw new Error('Expected [--root product-root] [--json inventory.json] [--header desktop_glyphs.hpp]');
    options.set(key, value);
  }
  const root = path.resolve(options.get('--root') ?? path.join(path.dirname(fileURLToPath(import.meta.url)), '..'));
  const inventory = collectDesktopGlyphs(root);
  const json = JSON.stringify(inventory, null, 2) + '\n';
  if (options.has('--json')) putOutput(root, options.get('--json'), json);
  if (options.has('--header')) putOutput(root, options.get('--header'), desktopGlyphsHeader(inventory));
  process.stdout.write(options.has('--json')
    ? 'PASS ' + inventory.codepoints.length + ' product glyphs from ' + inventory.inputs.length + ' inputs\n'
    : json);
}

if (path.resolve(process.argv[1] ?? '') === fileURLToPath(import.meta.url)) main();
