// The contract is deliberately conservative: shared implementation changes invalidate
// consumers too. Git revisions, documentation and test bodies are not build inputs.
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, readdirSync, mkdirSync, writeFileSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { collectDesktopGlyphs, desktopGlyphsHeader } from './compile_desktop_glyphs.mjs';

export function writeChanged(file, value) {
    if (existsSync(file) && readFileSync(file, 'utf8') === value) return;
    mkdirSync(path.dirname(file), { recursive: true });
    writeFileSync(file, value);
}

function scan(directory, accept) {
    if (!existsSync(directory)) return [];
    return readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
        const file = path.join(directory, entry.name);
        if (entry.isSymbolicLink()) throw new Error('Contract inputs cannot be symlinks: ' + file);
        return entry.isDirectory() ? scan(file, accept) : accept(file) ? [file] : [];
    });
}

export function fingerprint(root, spec) {
    const inputs = new Set(spec.sources.map(file => path.resolve(root, file)));
    // This inventory detects added/removed headers, including private layouts. It
    // never supplies CMake's source list; targets retain explicit registration.
    for (const directory of ['include', 'src'])
        for (const file of scan(path.join(root, directory), file => /\.(h|hpp|hxx|inl|inc|ipp)$/.test(file))) inputs.add(file);
    for (const directory of ['assets/data', 'assets/simulation'])
        for (const file of scan(path.join(root, directory), file => /\.(json|txt|tsv)$/.test(file) && path.basename(file) !== 'SOURCES.json')) inputs.add(file);
    const hash = createHash('sha256');
    hash.update('Ark shared library contract v1\0' + JSON.stringify(spec.settings) + '\0');
    // The resource DLL consumes this generated header, whose inventory includes
    // desktop EXE text too. Reuse the generator's exact input contract without
    // reading a build output or introducing an ordering/circular dependency.
    if (spec.desktopGlyphs)
        hash.update(desktopGlyphsHeader(collectDesktopGlyphs(root)) + '\0');
    for (const file of [...inputs].sort()) {
        hash.update(path.relative(root, file).replaceAll('\\', '/') + '\0');
        hash.update(readFileSync(file));
        hash.update('\0');
    }
    return hash.digest('hex');
}

export function contractHeader(identity, modules) {
    return '// Generated by shared_library_contract.mjs; no runtime file dependency.\n#pragma once\n' +
        '#define ARK_LIBRARY_CONTRACT "' + identity + '"\n' +
        'inline constexpr const char* ark_library_modules[] = {' + modules.map(JSON.stringify).join(',') + '};\n';
}

function fileHash(file) { return createHash('sha256').update(readFileSync(file)).digest('hex'); }

export function verify(root, spec, manifest) {
    if (manifest.version !== 1 || manifest.identity !== fingerprint(root, spec))
        throw new Error('Shared library sources/settings changed or the last build did not complete.');
    if (manifest.artifacts.length !== spec.artifacts.length) throw new Error('Shared library inventory changed.');
    for (const [index, file] of spec.artifacts.entries()) {
        const artifact = manifest.artifacts[index];
        if (artifact.file !== file || !existsSync(file) || artifact.sha256 !== fileHash(file))
            throw new Error('Shared library is missing, replaced or from an incomplete build: ' + file);
    }
    return manifest.identity;
}

export function run(args) {
    const [mode, root, directory, output] = args;
    if (!['prepare', 'publish', 'check', 'check-executable'].includes(mode) || !root || !directory)
        throw new Error('Usage: shared_library_contract.mjs <prepare|publish|check|check-executable> ROOT LIBRARY_BUILD [HEADER|EXE]');
    const spec = JSON.parse(readFileSync(path.join(directory, 'ArkLibraryInputs.json'), 'utf8'));
    const header = path.join(directory, 'contract', 'ark_library_contract.hpp');
    const manifestPath = path.join(directory, 'ArkLibraryContract.json');
    if (mode === 'prepare') {
        writeChanged(header, contractHeader(fingerprint(root, spec), spec.modules));
    } else if (mode === 'publish') {
        const identity = fingerprint(root, spec);
        if (!readFileSync(header, 'utf8').includes('#define ARK_LIBRARY_CONTRACT "' + identity + '"'))
            throw new Error('Shared inputs changed during compilation; repeat the shared library build.');
        writeChanged(manifestPath, JSON.stringify({version: 1, identity,
            artifacts: spec.artifacts.map(file => ({file, sha256: fileHash(file)}))}, null, 2) + '\n');
    } else {
        try {
            const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
            verify(root, spec, manifest);
            if (mode === 'check' && output)
                writeChanged(output, contractHeader(manifest.identity, spec.modules));
        } catch (error) {
            // A failed post-link check must not leave an apparently runnable EXE
            // compiled against headers that changed after the pre-build check.
            if (mode === 'check-executable' && output && existsSync(output)) unlinkSync(output);
            throw error;
        }
    }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    try { run(process.argv.slice(2)); }
    catch (error) {
        process.stderr.write('Ark-Village: ' + error.message + '\n' +
            'Rebuild with: node scripts/build_product.mjs <desktop-debug|desktop-release|headless-debug|headless-release>\n');
        process.exitCode = 1;
    }
}
