const archivePaths = require('../work_archive_paths.cjs').forTool(__filename);
// GLText生产者复用旧证据；本批只认证有限消费者与池保留边界。
const fs=archivePaths.require('fs'),path=archivePaths.require('path'),crypto=archivePaths.require('crypto'),cp=archivePaths.require('child_process');
if(process.argv.length!==2)throw Error('no arguments');
const root=path.resolve(archivePaths.workDir,'../..'),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>fs.readFileSync(path.join(root,p));
const dll=read('DungeonVillageEXE/GameAssembly.dll'),metadata=read('DungeonVillageEXE/KairoGames_Data/il2cpp_data/Metadata/global-metadata.dat');
if(hash(dll)!=='9cf4bb10d55afe6898bf9b82d9016d328cce623a7e4743623eb3df720b55ab1a'||hash(metadata)!=='80e17b3c1f7b7a844d64be27918e16cacfab05d70d7f33c0a61e45d830d7a369')throw Error('source identity');
const run=(p,args=[])=>cp.execFileSync(process.execPath,[path.join(archivePaths.workDir,p),...args],{encoding:'utf8',maxBuffer:1024*1024});
const methods=run('inspect.cjs',['manifest']).trim().split('\n').map(JSON.parse),bindings=JSON.parse(run('bindings.cjs'));
if(bindings.entries.map(e=>e.method).join(',')!=='Add,get_Item'||bindings.entries[0].class_instantiation!==bindings.entries[1].class_instantiation)throw Error('pool generic operations');
const prior=read('work/steam-font-backend-contract/EVIDENCE.json'),j=JSON.parse(prior),producer=j.windows.find(w=>w.key==='drawFirst');
if(!producer||producer.rva!==0x7663d0||producer.bytes!==4096||hash(dll.subarray(producer.offset,producer.offset+producer.bytes))!==producer.sha256)throw Error('prior producer identity');
const dump=read('work/persistence-replay-analysis/exe/dumper/dump.cs'),text=dump.toString('utf8'),a=text.indexOf('private class Graphics.GLText // TypeDefIndex: 892'),end=text.indexOf('// Methods',a);
if(a<0||end<a)throw Error('GLText definition');const fields=text.slice(a,end).split(/\r?\n/).filter(s=>/^\s+public .*; \/\//.test(s)).map(s=>s.trim());if(fields.length!==9)throw Error('GLText fields');
const evidence={scope:'GLText enqueue→flush GUI.Label→count retirement and retained references; static only',dll_sha256:hash(dll),metadata_sha256:hash(metadata),methods,method_count:methods.length,unique_bytes:methods.reduce((s,m)=>s+m.bytes,0),producer:{prior_path:'../steam-font-backend-contract/EVIDENCE.json',prior_sha256:hash(prior),window:producer,consumer_start_va:0x10767043,consumer_end_va:0x10767173},bindings,field_source:{path:'../persistence-replay-analysis/exe/dumper/dump.cs',sha256:hash(dump),fields},contracts:{flush_gate:['offscreen Unity-object-null','glRender true','isGUI true'],mesh_only_preserves_text:true,normal_flush_resets_active_count:true,normal_flush_clears_pool_or_text_font_references:false,dispose_false_clears_mesh_only:true,exceptions_not_transactional:true},limits:['No proof of active backend or live CJK glyph identity','GUI.Label is final managed consumer, Unity rasterization stays external','Pool capacity is historical peak; no universal bound or whole-process no-leak claim','Image.TextRenderTask branch is outside this batch'],scripts:['inspect.cjs','bindings.cjs','audit.cjs'].map(p=>{const b=fs.readFileSync(path.join(archivePaths.workDir,p));return {path:p,bytes:b.length,sha256:hash(b)};})};
fs.writeFileSync(path.join(archivePaths.workDir,'EVIDENCE.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({methods:methods.length,bytes:evidence.unique_bytes,reused_producer_bytes:producer.bytes,generic_bindings:bindings.entries.length,fields:fields.length}));
