# Consumer configurations import the independently built module targets. They never
# compile another copy of the common libraries or silently select a different ABI.
set(ARK_COMMON_LIBRARY_DIR "${PROJECT_SOURCE_DIR}/build/shared-libraries" CACHE PATH
    "Configured and built common Ark library directory")
if(NOT EXISTS "${ARK_COMMON_LIBRARY_DIR}/ArkLibraryBuild.cmake" OR
   NOT EXISTS "${ARK_COMMON_LIBRARY_DIR}/ArkLibraries.cmake")
    message(FATAL_ERROR "Build the shared-libraries preset before configuring consumers")
endif()
include("${ARK_COMMON_LIBRARY_DIR}/ArkLibraryBuild.cmake")
if(NOT ARK_LIBRARY_COMPILER_ID STREQUAL CMAKE_CXX_COMPILER_ID OR
   NOT ARK_LIBRARY_COMPILER_VERSION STREQUAL CMAKE_CXX_COMPILER_VERSION OR
   NOT ARK_LIBRARY_POINTER_SIZE STREQUAL CMAKE_SIZEOF_VOID_P)
    message(FATAL_ERROR "Consumer compiler/architecture does not match the common libraries")
endif()
file(REAL_PATH "${ARK_LIBRARY_COMPILER}" ark_library_compiler_real)
file(REAL_PATH "${CMAKE_CXX_COMPILER}" ark_consumer_compiler_real)
if(NOT ark_library_compiler_real STREQUAL ark_consumer_compiler_real)
    message(FATAL_ERROR "Consumer must use the common libraries' C++ compiler")
endif()
if(NOT ARK_BUILD_PROFILE)
    string(TOLOWER "${CMAKE_BUILD_TYPE}" ark_profile_type)
    if(ARK_BUILD_DESKTOP)
        set(ARK_BUILD_PROFILE "desktop-${ark_profile_type}")
    else()
        set(ARK_BUILD_PROFILE "headless-${ark_profile_type}")
    endif()
endif()
include("${ARK_COMMON_LIBRARY_DIR}/ArkLibraries.cmake")
string(TOUPPER "${ARK_LIBRARY_BUILD_TYPE}" ark_library_config)
get_property(ark_imported_targets DIRECTORY PROPERTY IMPORTED_TARGETS)
foreach(target IN LISTS ark_imported_targets)
    if(NOT target MATCHES "^ark_" OR
       (target STREQUAL "ark_world_ui_test_support" AND NOT ARK_BUILD_DESKTOP))
        continue()
    endif()
    foreach(kind IMPORTED_LOCATION IMPORTED_IMPLIB)
        if(kind STREQUAL "IMPORTED_IMPLIB" AND NOT WIN32)
            continue()
        endif()
        get_target_property(artifact ${target} "${kind}_${ark_library_config}")
        if(NOT artifact OR NOT EXISTS "${artifact}")
            message(FATAL_ERROR "Missing common library artifact for ${target}: ${artifact}. Build shared-libraries first.")
        endif()
    endforeach()
endforeach()
if(ARK_BUILD_DESKTOP)
    # Consumers use the single generated desktop inventory beside the common libraries.
    # They do not rescan sources or silently generate an incompatible private font list.
    set(ARK_DESKTOP_GENERATED_DIR "${ARK_COMMON_LIBRARY_DIR}/desktop-generated")
    set(ARK_DESKTOP_GLYPH_HEADER "${ARK_DESKTOP_GENERATED_DIR}/desktop_glyphs.hpp")
    set(ARK_DESKTOP_GLYPH_INVENTORY "${ARK_DESKTOP_GENERATED_DIR}/desktop_glyphs.json")
    if(NOT EXISTS "${ARK_DESKTOP_GLYPH_HEADER}" OR NOT EXISTS "${ARK_DESKTOP_GLYPH_INVENTORY}")
        message(FATAL_ERROR "Missing common desktop glyph inventory. Configure and build the shared-libraries preset before configuring desktop consumers.")
    endif()
endif()
if(ARK_BUILD_DESKTOP AND NOT ARK_DESKTOP_FONT)
    find_file(ark_common_font NAMES default.otf default.ttf
        HINTS "${ARK_SHARED_RUNTIME_DIRECTORY}/fonts" NO_DEFAULT_PATH NO_CACHE)
    if(ark_common_font)
        set(ARK_DESKTOP_FONT "${ark_common_font}" CACHE FILEPATH "Common desktop font" FORCE)
    endif()
endif()
message(STATUS "Using common ${ARK_LIBRARY_BUILD_TYPE} libraries: ${ARK_COMMON_LIBRARY_DIR}")
