// 核默认GameSkin→GUISkin脚本→Arial引用；只读有限对象前缀，不导出字体字节。
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),read=p=>fs.readFileSync(path.join(root,p));
const coverage=JSON.parse(read('assets/IMAGE_COVERAGE.json')),name='Resources/unity default resources',container=read('DungeonVillageEXE/KairoGames_Data/'+name),expected=coverage.containers.find(c=>c.kind==='UnitySerializedFile'&&c.path===name);
if(!expected||container.length!==expected.bytes||sha(container)!==expected.sha256)throw Error('container identity');
function obj(id,type){const r=coverage.records.find(r=>r.id==='EXE:'+name+':pathID='+id);if(!r||r.class_id!==type||r.offset+r.bytes>container.length)throw Error('object identity');const b=container.subarray(r.offset,r.offset+r.bytes);if(sha(b)!==r.sha256)throw Error('object hash');return {r,b};}
function str(b,p,max=128){if(p+4>b.length)throw Error('string offset');const n=b.readUInt32LE(p);if(n>max||p+4+n>b.length)throw Error('string length');return {offset:p,bytes:n,text:b.toString('utf8',p+4,p+4+n),end:p+4+n};}
function ptr(b,p){if(p+12>b.length)throw Error('pointer');const id=b.readBigInt64LE(p+4);if(id>BigInt(Number.MAX_SAFE_INTEGER)||id<0)throw Error('path id');return {offset:p,file_id:b.readInt32LE(p),path_id:Number(id)};}
const skin=obj(11000,114),script=obj(12001,115),font=obj(10102,128);
const skinName=str(skin.b,28),scriptRef=ptr(skin.b,16),fontRef=ptr(skin.b,40),boxName=str(skin.b,52),fontName=str(font.b,0);
if(skinName.text!=='GameSkin'||skinName.end!==40||scriptRef.file_id!==0||scriptRef.path_id!==12001||fontRef.file_id!==0||fontRef.path_id!==10102||boxName.text!=='box'||fontName.text!=='Arial')throw Error('skin/font structural anchors');
const scriptName=str(script.b,0),klass=str(script.b,32),namespace=str(script.b,44),assembly=str(script.b,60);
if(scriptName.text!=='GUISkin'||klass.text!=='GUISkin'||namespace.text!=='UnityEngine'||assembly.text!=='UnityEngine.IMGUIModule.dll'||((assembly.end+3)&~3)!==script.b.length)throw Error('MonoScript identity');
const dll=read('DungeonVillageEXE/GameAssembly.dll'),meta=read('DungeonVillageEXE/KairoGames_Data/il2cpp_data/Metadata/global-metadata.dat'),index=JSON.parse(read('work/persistence-replay-analysis/exe/methods.json'));
if(sha(dll)!=='9cf4bb10d55afe6898bf9b82d9016d328cce623a7e4743623eb3df720b55ab1a'||sha(meta)!=='80e17b3c1f7b7a844d64be27918e16cacfab05d70d7f33c0a61e45d830d7a369')throw Error('PE identity');
const map=(va,n=4)=>{const r=va-index.base,s=index.sections.find(s=>r>=s.rva&&r+n<=s.rva+s.rawSize);if(!s||s.raw+r-s.rva+n>dll.length)throw Error('PE range');return s.raw+r-s.rva;};
const lo=meta.readUInt32LE(8),lb=meta.readUInt32LE(12),data=meta.readUInt32LE(16),db=meta.readUInt32LE(20);
const strings=[0x11100a7c,0x110f60c8,0x110ff660].map(va=>{const e=dll.readUInt32LE(map(va)),i=(e>>>1)&0xfffffff;if(e>>>29!==5||i*8+8>lb)throw Error('literal');const n=meta.readUInt32LE(lo+i*8),off=meta.readUInt32LE(lo+i*8+4);if(n>256||off+n>db)throw Error('literal bounds');return {va,index:i,bytes:n,text:meta.toString('utf8',data+off,data+off+n)};});
const aliases=index.methods.filter(m=>m.va===0x101c3260&&m.type==='UnityEngine.GUISkin');if(aliases.length!==1||aliases[0].signature!=='public Font get_font() { }')throw Error('shared accessor identity');
const dump=read('work/persistence-replay-analysis/exe/dumper/dump.cs'),text=dump.toString('utf8');const fields=[];
for(const [type,names] of [['public sealed class GUISkin : ScriptableObject // TypeDefIndex: 5200',['private Font m_Font;','private GUIStyle m_box;']],['public class Graphics // TypeDefIndex: 904',['internal bool fontScaleOffsetEnable_;','protected int useFontTextureCount_;','protected List<bool> useFontTextureStack_;']],['public abstract class IApplication : MonoBehaviour // TypeDefIndex: 925',['private static Font initFont_;']],['public class Config // TypeDefIndex: 551',['public static bool UNITY_EDITOR;']]]){if(names.length===0)continue;const a=text.indexOf(type);if(a<0)throw Error('field type '+type);const e=text.indexOf('// Methods',a);const lines=text.slice(a,e).split(/\r?\n/);for(const name of names){const line=lines.find(l=>l.includes(name));if(!line)throw Error('field '+name);fields.push(line.trim());}}
const output={container:{path:'DungeonVillageEXE/KairoGames_Data/'+name,bytes:container.length,sha256:sha(container)},objects:[skin,script,font].map(o=>({id:o.r.id,offset:o.r.offset,bytes:o.r.bytes,sha256:o.r.sha256})),game_skin:{name:skinName,script:scriptRef,font:fontRef,next_style:boxName},script:{name:scriptName,class:klass,namespace,assembly},font:{name:fontName,remaining_bytes:font.b.length-fontName.end,limitation:'Only object identity; does not certify CJK glyphs, OS fallback or active skin'},metadata_field_source:{path:'../persistence-replay-analysis/exe/dumper/dump.cs',sha256:sha(dump),fields},plugin_strings:strings,shared_accessor:aliases[0]};
console.log(JSON.stringify(output,null,2));
